### ISSUE TITLE
Cwerg - lightweight low-level compiler (instruction emitter) as inspiration

### ISSUE THREAD

**Issue by dumblob** [mobarski/morty#6]
Today I accidentally discovered https://github.com/robertmuth/Cwerg . I didn't look into it in much detail, but it seemed there could be some knowledge hidden which morty could leverage.

Feel free to close this issue as it's only informative and has no actionable items.

**Comment by mobarski** [comment]
Thanks! It might be useful in the compilation toolchain as a light compiler option for the transpiler. It requires ARMv6 so it might be used for Raspberry Pi but it won't work with BBC micro:bit (and I would like to target them both). I don't have an idea (yet) how I could leverage some knowledge from the project.

**Comment by dumblob** [comment]
Another really advanced emitter is [fasmg](https://flatassembler.net/ ) (example:  https://github.com/tgrysztar/fasmg/blob/master/packages/webassembly/wasm.inc ) which reminds a full-featured language rather then a dumb emitter. Btw. `g` in fasmg is important as its predecessor fasm (no `g` here) didn't have the cool advanced game-changing features like resolving of cycles in expressions etc.

Btw. you might be interested in a [language literally based around vastly extending assembler by a highly advanced type system](https://github.com/grassator/mass ) and likely the fastest existing non-JIT **very universal** (across languages and across platforms) virtual machine [minivm](https://github.com/fastvm/minivm ).
